# .cargo/config.toml

# This is required for wasm-bindgen to work.
[target.wasm32-unknown-unknown]
rustflags = ["--cfg=web_sys_unstable_apis"]

# Replace the `getrandom` crate with a version that has the `js` feature enabled.
[replace]
"getrandom:0.2.12" = { git = "https://github.com/rust-random/getrandom", rev = "v0.2.12" }
"getrandom:0.2.10" = { git = "https://github.com/rust-random/getrandom", rev = "v0.2.10" }
"getrandom:0.2.9" = { git = "https://github.com/rust-random/getrandom", rev = "v0.2.9" }
"getrandom:0.2.8" = { git = "https://github.com/rust-random/getrandom", rev = "v0.2.8" }
"getrandom:0.2.7" = { git = "https://github.com/rust-random/getrandom", rev = "v0.2.7" }
"getrandom:0.2.6" = { git = "https://github.com/rust-random/getrandom", rev = "v0.2.6" }
"getrandom:0.2.5" = { git = "https://github.com/rust-random/getrandom", rev = "v0.2.5" }
"getrandom:0.2.4" = { git = "https://github.com/rust-random/getrandom", rev = "v0.2.4" }
"getrandom:0.2.3" = { git = "https://github.com/rust-random/getrandom", rev = "v0.2.3" }
"getrandom:0.2.2" = { git = "https://github.com/rust-random/getrandom", rev = "v0.2.2" }
"getrandom:0.2.1" = { git = "https://github.com/rust-random/getrandom", rev = "v0.2.1" }
"getrandom:0.2.0" = { git = "https://github.com/rust-random/getrandom", rev = "v0.2.0" }
"getrandom:0.1.16" = { git = "https://github.com/rust-random/getrandom", rev = "v0.1.16" } 