[package]
name = "shared"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
bincode = "1.3.3"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
bevy = { version = "0.14.0", default-features = false } 